version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.0
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
    volumes:
      - forpostgres:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  account:
    build: ./account
    environment:
      TEST_DB_URL: ""
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  crypto:
    build: ./crypto
    environment:
      CRYPTO_COMPARE_KEY: 8b0b296373b86403560d64ab9a1e29ae35ab088e87ef5745f554ef5d0a2673be
    ports:
      - "8181:8181"
    depends_on:
      - account
  
  gateway:
    build: ./gateway
    ports:
      - "8282:8282"
    depends_on:
      - account
      - crypto

volumes:
  forpostgres:

networks:
  postgres:
    driver: bridge
    