version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.0
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - forpostgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "euseew.maxim2015@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "root"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
    depends_on:
      - postgres

  account:
    build: ./account
    environment:
      TEST_DB_URL: ""
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  crypto:
    build: ./crypto
    environment:
      CRYPTO_COMPARE_KEY: 8b0b296373b86403560d64ab9a1e29ae35ab088e87ef5745f554ef5d0a2673be
    ports:
      - "8181:8181"
    depends_on:
      - account
  
  gateway:
    build: ./gateway
    ports:
      - "8282:8282"
    depends_on:
      - account
      - crypto

volumes:
  forpostgres:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
    