database:
  host: postgres://admin:root@postgres:5432/database

http:
  session_domain: account

server:
  port: :8080

env:
  mode: debug

dependencies:
  crypto_service:
    host: "localhost:8181"
    endpoints:
      current_prices: "v1/crypto/prices"