server:
  port: :8080

env:
  mode: debug

validation:
  password:
    min_length: 6
    max_length: 20
  login:
    min_length: 6
    max_length: 20

dependencies:
  crypto_service:
    endpoints:
      current_prices: "/v1/crypto/prices"