database:
  host: postgres://postgres:maxgold123@localhost:5432/postgres

http:
  session_domain: account

server:
  port: :8080

env:
  mode: debug

dependencies:
  crypto_service:
    host: "http://localhost:8181"
    endpoints:
      current_prices: "/v1/crypto/prices"