database:
  host: postgres://postgres:maxgold123@localhost:5432/postgres

http:
  session_domain: appdomain
  secret: secret

server:
  port: :8181
  appid: appid
  key: secret_key

env:
  mode: debug
  
auth:
  cas: https://domain