http:
  session_domain: gateway

server:
  port: :8282
  secret_key: dfg4sdgssefg34egdgghdfgd

env:
  mode: debug
  
auth:
  jwtexpseconds: 360000000

account_service:
  url: http://localhost:8080/v1/account

crypto_service:
  url: http://localhost:8181/v1/crypto
