// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "euseew.maxim2015@yandex.ru"
        },
        "license": {
            "name": "EUS"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/diff": {
            "get": {
                "description": "Getting price difference in USD and % between current date and some historical date\nUse query params to configure it right",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crypto"
                ],
                "summary": "Price difference",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Default: days. What time you want to track. All variants: days, hours, minutes",
                        "name": "timebase",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Crypto currency symbol. Example: BTC",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "One default currency to convert crypto symbol to. Example: USD",
                        "name": "symbolTo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Default: 1. Offset from current date. For example if timebase=days and offset=3 you get price difference between current day and day that was 3 days ago",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PriceDifference"
                        }
                    }
                }
            }
        },
        "/history": {
            "get": {
                "description": "Getting Open High Low Close Volume info about given symbol\nUses different timebases depends on timebase query param",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crypto"
                ],
                "summary": "Get OHLCV history info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "What time you want to track. All variants: days, hours, minutes",
                        "name": "timebase",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Crypto currency symbol. Example: BTC",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "One default currency to convert crypto symbol to. Example: USD",
                        "name": "symbolTo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "How many records you want to get. For example: timebase=days limit=5 means that you get 5 days history from current date",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cryptocompare.HistoricalData"
                        }
                    }
                }
            }
        },
        "/prices": {
            "get": {
                "description": "Retrieves latest prices in different currencies for given crypto symbol\nEvery field in Prices response object is your given \"symbolsTo\" value.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crypto"
                ],
                "summary": "Get latest prices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Crypto currency symbol. Example: BTC",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "One or many default currencies to convert crypto symbol to. Example 1: USD | Example 2: USD,JPY",
                        "name": "symbolsTo",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cryptocompare.Prices"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cryptocompare.HistoricalData": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cryptocompare.OHLCVItem"
                    }
                },
                "timeFrom": {
                    "type": "integer"
                },
                "timeTo": {
                    "type": "integer"
                }
            }
        },
        "cryptocompare.OHLCVItem": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "low": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "time": {
                    "type": "integer"
                },
                "volumeFrom": {
                    "type": "number"
                },
                "volumeTo": {
                    "type": "number"
                }
            }
        },
        "cryptocompare.Prices": {
            "type": "object",
            "properties": {
                "prices": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                }
            }
        },
        "models.PriceDifference": {
            "type": "object",
            "properties": {
                "diff": {
                    "type": "number"
                },
                "percents": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1/crypto",
	Schemes:          []string{},
	Title:            "Crypto Service API",
	Description:      "Swagger API for Golang Project Crypto Service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
