basePath: /v1/crypto
definitions:
  cryptocompare.HistoricalData:
    properties:
      data:
        items:
          $ref: '#/definitions/cryptocompare.OHLCVItem'
        type: array
      timeFrom:
        type: integer
      timeTo:
        type: integer
    type: object
  cryptocompare.OHLCVItem:
    properties:
      close:
        type: number
      high:
        type: number
      low:
        type: number
      open:
        type: number
      time:
        type: integer
      volumeFrom:
        type: number
      volumeTo:
        type: number
    type: object
  cryptocompare.Prices:
    properties:
      prices:
        additionalProperties:
          type: number
        type: object
    type: object
  models.PriceDifference:
    properties:
      diff:
        type: number
      percents:
        type: number
    type: object
info:
  contact:
    email: euseew.maxim2015@yandex.ru
    name: API Support
  description: Swagger API for Golang Project Crypto Service.
  license:
    name: EUS
  termsOfService: http://swagger.io/terms/
  title: Crypto Service API
  version: "1.0"
paths:
  /diff:
    get:
      consumes:
      - application/json
      description: |-
        Getting price difference in USD and % between current date and some historical date
        Use query params to configure it right
      parameters:
      - description: 'Default: days. What time you want to track. All variants: days,
          hours, minutes'
        in: query
        name: timebase
        type: string
      - description: 'Crypto currency symbol. Example: BTC'
        in: query
        name: symbol
        required: true
        type: string
      - description: 'One default currency to convert crypto symbol to. Example: USD'
        in: query
        name: symbolTo
        required: true
        type: string
      - description: 'Default: 1. Offset from current date. For example if timebase=days
          and offset=3 you get price difference between current day and day that was
          3 days ago'
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PriceDifference'
      summary: Price difference
      tags:
      - crypto
  /history:
    get:
      consumes:
      - application/json
      description: |-
        Getting Open High Low Close Volume info about given symbol
        Uses different timebases depends on timebase query param
      parameters:
      - description: 'What time you want to track. All variants: days, hours, minutes'
        in: query
        name: timebase
        required: true
        type: string
      - description: 'Crypto currency symbol. Example: BTC'
        in: query
        name: symbol
        required: true
        type: string
      - description: 'One default currency to convert crypto symbol to. Example: USD'
        in: query
        name: symbolTo
        required: true
        type: string
      - description: 'How many records you want to get. For example: timebase=days
          limit=5 means that you get 5 days history from current date'
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cryptocompare.HistoricalData'
      summary: Get OHLCV history info
      tags:
      - crypto
  /prices:
    get:
      consumes:
      - application/json
      description: |-
        Retrieves latest prices in different currencies for given crypto symbol
        Every field in Prices response object is your given "symbolsTo" value.
      parameters:
      - description: 'Crypto currency symbol. Example: BTC'
        in: query
        name: symbol
        required: true
        type: string
      - description: 'One or many default currencies to convert crypto symbol to.
          Example 1: USD | Example 2: USD,JPY'
        in: query
        name: symbolsTo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cryptocompare.Prices'
      summary: Get latest prices
      tags:
      - crypto
swagger: "2.0"
